# Generated by Django 3.2.8 on 2022-01-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdata',
            name='profilepic',
            field=models.ImageField(blank=True, default='/images/ProfileDefault.jpg', null=True, upload_to='images'),
        ),
    ]
