# Generated by Django 3.2.8 on 2022-02-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_buildingdata_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='appltypes',
        ),
    ]
