# Generated by Django 3.2.8 on 2022-02-10 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_remove_flat_appltypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appltype', models.TextField(choices=[('Air Conditioner', 'Air Conditioner'), ('Computer', 'Computer'), ('LED', 'LED'), ('CFL', 'CFL'), ('Microwave', 'Microwave'), ('Washing Machine', 'Washing Machine'), ('Ceiling Fan', 'Ceiling Fan'), ('Refrigerator', 'Refrigerator'), ('Air Fryer', 'Air Fryer'), ('Chimney', 'Chimney'), ('Geyser', 'Geyser'), ('OTG', 'OTG'), ('Oven', 'Oven'), ('Electric Stove', 'Electric Stove'), ('BEV Charger', 'BEV Charger'), ('Television', 'Television'), ('Room Heater', 'Room Heater'), ('Electric Kettle', 'Electric Kettle')], default='Appliance Type...', max_length=200, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('modelname', models.CharField(max_length=500, null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.flat')),
            ],
        ),
    ]
