# Generated by Django 3.2.8 on 2022-02-10 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_appliancedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancedata',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.flat'),
        ),
    ]
