# Generated by Django 3.2.8 on 2022-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_alter_appliancedata_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancedata',
            name='rating',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, null=True),
        ),
    ]
