# Generated by Django 3.2.8 on 2022-04-01 03:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_rename_lastyrbill_flat_lastyrunits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='lastyrunits',
        ),
        migrations.AddField(
            model_name='flat',
            name='lastyr_units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True), blank=True, null=True, size=12),
        ),
    ]
