# Generated by Django 3.2.8 on 2022-04-02 04:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_auto_20220401_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='threeyrbfr_units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True), blank=True, null=True, size=12),
        ),
        migrations.AddField(
            model_name='flat',
            name='twoyrbfr_units',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True), blank=True, null=True, size=12),
        ),
    ]
